# Should have a step to deploy to gh-pages

name: Workflow
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Make all
      working-directory: ./
      run: ls
